// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJUmsFJW1E86Zs2RQ3OrBtvyXhsh1FyA',
    appId: '1:834030680551:web:5b50d08c8ca4380c312542',
    messagingSenderId: '834030680551',
    projectId: 'talkdoraemon',
    authDomain: 'talkdoraemon.firebaseapp.com',
    storageBucket: 'talkdoraemon.appspot.com',
    measurementId: 'G-67PJM1DBEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QqqvgEKRPnMWcCNMdyLOzedJdYHaE_A',
    appId: '1:834030680551:android:01058292bd91514a312542',
    messagingSenderId: '834030680551',
    projectId: 'talkdoraemon',
    storageBucket: 'talkdoraemon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAejsN8a9Zy-0IW4euK9cvuQrUJ8D-Vv_k',
    appId: '1:834030680551:ios:995fcf7d495b4889312542',
    messagingSenderId: '834030680551',
    projectId: 'talkdoraemon',
    storageBucket: 'talkdoraemon.appspot.com',
    iosBundleId: 'com.arrijal.talkdoraemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAejsN8a9Zy-0IW4euK9cvuQrUJ8D-Vv_k',
    appId: '1:834030680551:ios:995fcf7d495b4889312542',
    messagingSenderId: '834030680551',
    projectId: 'talkdoraemon',
    storageBucket: 'talkdoraemon.appspot.com',
    iosBundleId: 'com.arrijal.talkdoraemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJUmsFJW1E86Zs2RQ3OrBtvyXhsh1FyA',
    appId: '1:834030680551:web:e29f4cd7e4769af2312542',
    messagingSenderId: '834030680551',
    projectId: 'talkdoraemon',
    authDomain: 'talkdoraemon.firebaseapp.com',
    storageBucket: 'talkdoraemon.appspot.com',
    measurementId: 'G-5QH2GC2YC7',
  );
}
